apiVersion: v1
kind: Secret
metadata:
  name: memphis-demo-creds
  namespace: memphis-demo
type: Opaque
data:
  MEMPHIS_USERNAME: {{ "root" | b64enc | quote }} 
  MEMPHIS_CT: {{ "XrHmszw6rgm8IyOPNNTy" | b64enc | quote }}
